### ISSUE TITLE
چند پیشنهاد

### ISSUE THREAD

**Issue by farooqkz** [Ferdowsi-lang/Ferdowsi-Python-Interpreter#17]
<div dir="rtl">
سلام و خدا قوت!

از طریق علیرضا آهنی با این پروژه آشنا شدم

سعی میکنم توی گفته‌هام صادق و رک باشم شما هم سعی کنید ناراحت نشید!

داشتم به علیرضا آهنی می‌گفتم که همچین زبانی عملا کاربردی نیست و بدرد هیچ‌کاری نمیخوره

مگر به عنوان یک پروژه جهت بالا بردن تجربه برنامه‌نویس‌های پروژه...

خب واقعا هم همینطوره اما بعد ایده‌ای به ذهنم خطور کرد!

درسته که این پروژه به کار صنعت و اینا نمیاد

اما همچین چیزی بشدت به کار آموزش میاد

احتمالا به ذهن خودتون هم این رسیده

اما منظور بنده از آموزش، آموزش برای بزرگسال‌ها و نوجوانان نیست(تقریبا)

همچین زبانی اگر توسعه داده بشه خیلی به کار آموزش برنامه نویسی به بچه دبستانی‌ها میاد.

کسایی که تازه خوندن و نوشتن رو یاد گرفتن و با اینکار میتونن چند تا تیر رو هم زمان بزنن!

 - خوندن و نوشتنشون قوی‌تر بشه
 - ریاضی‌شون قوی‌تر بشه و بهتر یاد بگیرن
 - تفکر منطقی رو یاد بگیرن که در زندگی‌شون بکار میاد حتی اگر نخوان برنامه‌نویسی یادبگیرن بعدا
 - برنامه‌نویسی هم یاد میگیرن به هر حال

فکر میکنم دلیل همه موارد روشنه جز دومی. این رو من تجربی متوجه شدم. یک مثال بارز میزنم:

علیرضا آهنی!

با اینکه تازه از دبستان فارغ شده اما به خاطر اینکه قبلا برنامه‌نویسی کار میکرده الآن خیلی از مفاهیم

ریاضی رو بلد هست و تنها چیزی که از این مفاهیم نمیدونه اسمشون،نمادشون و طرز استفاده‌شون در ریاضیات هست

اگر این سه مورد رو بهش بگی اون مفهوم ریاضی رو خیلی سریع میگیره. چرا چون از قبل بلد بوده مفهوم رو

حالا چه مفاهیمی رو میشه از طریق برنامه‌نویسی راحت و سرگرم‌کننده یاد گرفت؟

تا جایی که الآن یادم میاد تابع و تابع بازگشتی و مجموعه و ماتریس و چند تایی مرتب رو راحت میشه از طریق برنامه نویسی منتقل کرد

مفاهیم دیگه‌ای هم هستند مثل سیگما و پی

مفاهیم دیگه ای که از این طریق میشه راخت منتقلشون کرد مفاهیم خود علوم کامپیوتر هستند مثل

الگوریتم و پیچیدگی زمانی و مکانی و ساختمان داده

فکر کنید اگر یک بچه دبستانی حتی نصف این مفاهیم رو یاد بگیره چقدر داخل موفقیتش در ریاضی و علوم کامپیوتر در آینده تاثیر میزاره!

حالا برای اینکه به این اهداف برسیم من پیشنهاد میکنم که:
 - این زبان به پایتون نزدیک‌تر بشه
 - عادت های خوب رو یاد بده مثلا دندانه گزاری
 - یک محیط تحت وب که واکنش گرا باشه یعنی هم روی کامپیوتر خوب کار کنه و هم روی گوشی و تبلت
 - محیط تحت وب syntax highlighting داشته باشه
 - محیط تحت وب راهنما داشته باشه
 - با توجه به اینکه با بازی بچه‌ها بهتر یاد میگیرن بهتره چیزی شبیه لاکپشت پایتون وجود داشته باشه که اینجوری باعث میشه حتی مفاهیم بیشتری هم از ریاضیات غیر مستقیم آموزش داده بشه مثل زاویه یا توابع مثلثاتی
 - محیط تحت وب هم باید رنگ رنگی باشه که بچه‌های کوچیک رو جذب کنه

فعلا دیگه چیزی به ذهنم نمیرسه.
ببخشید طولانی شد!

**Comment by farooqkz** [comment]
<div dir="rtl">
گفتم تحت وب چون دیگه نیازی نیست که هم شما برای هر پلتفرم نرم‌افزار جدا بنویسید و هم کاربر نیازی نیست
نرم‌افزار خاصی نصب کنه. فقط یک مرورگر وب مدرن کافیه.

دیدم که بعضیا توی ویرگول پیشنهاد داده بودن که یک عدد ویرایشگر متن راست به چپ برای پروژه ساخته بشه
اما اگر تحت وب پیش برید یا از قبل ویرایشگر متن راست به چپ وجود داره و میتونید ماژولش رو استفاده کنید
و اگر وجود هم نداشته باشه درست کردشن خیلی راحت تر هست
مثلا میشه با یک همچین چیزی شروع کرد:
https://jsfiddle.net/owt7cayf/

**Comment by Paptoos** [comment]
سلام ، به نظر من قبلا تلاش هایی متعدد برای این کار شده ، اسکرچ یک زبان برنامه نویسی کودکان و برای دانشگاه ام آی تی هستش . زبان فارسی را هم پشتیبانی می کند .راستش رو بگم من خودم کلاس پنجمم ، و یادگیری خود پایتون یا حتی وب و جی اس و پی اچ پی برای یک بچه دبستانی سخت که نیست ، خیلی هم راحته . چون موقعی ای هست که در حال یادگیری است و به هیچ وجه فراموشش نمی شود ، برای هر سیستم عامل هم نوشتن کار اشتباهی هست ، پایتون می نویسیم یا هر زبانی بعد اکزه و دب و آر پی ام ازش خروجی می گیریم ، ولی ایده تحت وب ، ایده خوبی هست ، می تونه دو نسخه دسکتاپ و تحت وب داشته باشه ، مثل اسکرتچ ادیتور هم کار سختی نیست و من در حال پیاده سازی آن هستم ،

**Comment by Paptoos** [comment]
اگر هم برای آموزش باشه ، نیاز داره یک سری مقدمات زبان های برنامه نویسی قوی تر رو داشته باشه
**ولی چون بقیه زبان ها فارسی نیست ، اگر با این زبان به برنامه نویسی ورود کرد خیلی آدم گیج می شه**

**Comment by farooqkz** [comment]
شما احتمالا فقط خودتون رو میبینی و میگی سخت نیست و راحت هست.
خیلی ها هنوز در دبستان انگلیسی نمیدونن و علاوه بر اون پایتون با وجود سادگی اما برای یک بچه دبستانی میتونه یک مقدار پیچیده باشه
در مورد اسکرچ هم به نظر من محیطش و حتی خود زبان زیادی پیچیده هست و علاوه بر اون متنی نیست و کاربر تایپ نمیکنه

در مورد چیزی که بولد کردید هم موافقم اما از یک بچه دبستانی نمیشه توقع زیادی داشت
راه بهتر این هست که مثلا از زبانی مثل خود پایتون استفاده بشه که انگلیسی هم باشه و مثل بقیه زبان ها
اما این راه سخت‌تر هم هست و خب خیلی ها تن نمیدن به سختی یا اینطور بدتر یاد نمیگیرن

**Comment by farooqkz** [comment]
به هر حال دیگه خودتون میدونید

**Comment by Paptoos** [comment]
مشکلی نداره ، خوب این پیشنهادات رو شروع کنید

**Comment by Paptoos** [comment]
فقط مفسر چجوری روی وب اجرا بشه ؟

**Comment by AshkanLaei** [comment]
> فقط مفسر چجوری روی وب اجرا بشه ؟

یه نسخه جاوااسکریپت ازش میسازیم و هیچ مشکلی پیش نمیاد

>  مثل اسکرتچ ادیتور هم کار سختی نیست و من در حال پیاده سازی آن هستم ،

چرا زود تر نگفتی منم دارم میسازم! با گوگل بلاکلی

**Comment by farooqkz** [comment]
مفسر میتونه روی سرور اجرا بشه میشه هم یک نسخه جاوا اسکریپت ساخت که روی مرورگر کاربر اجرا بشه
اگر قرار باشه روی سرور اجرا بشه باید سهمیه بندی بشه

نمیدونم پایتون رو هم میشه مثل سی به جاوا اسکریپت کامپایل کرد یا نه

**Comment by AshkanLaei** [comment]
> نمیدونم پایتون رو هم میشه مثل سی به جاوا اسکریپت کامپایل کرد یا نه
شدن رو که میشه ولی کار عجیبیه چون خیلی راحت تر میشه از اول نوشت تو جاوااسکریپت

**Comment by farooqkz** [comment]
> > نمیدونم پایتون رو هم میشه مثل سی به جاوا اسکریپت کامپایل کرد یا نه
>  شدن رو که میشه ولی کار عجیبیه چون خیلی راحت تر میشه از اول نوشت تو جاوااسکریپت

دیگه بستگی به پروژه داره.

به هر حال اگر خواستید با جاوا اسکریپت بنویسید حتما کامپایل کنید به asm.js که سریع تر اجرا بشه برای کاربر

**Comment by farooqkz** [comment]
> چرا زود تر نگفتی منم دارم میسازم! با گوگل بلاکلی

با گوگل؟ پیشنهاد میکنم سمت گوگل نرید. به قول مقام رهبری عسل قاطی شده با سم هست
البته مقام رهبری در مورد ماهواره این رو گفتند اما مثال بهتری به ذهنم نرسید

**Comment by Paptoos** [comment]
من ادیتور لوکال دارم می سازم

**Comment by farooqkz** [comment]
ادیتور لوکال؟
خب چه کاریه؟ یه چیز تحت وب بسازید همه جا اجرا میشه
زحمتش هم کمتره

**Comment by Paptoos** [comment]
به نظر من وب خیلی کاربردیه ، ولی می توان نسخه دسکتاپ هم داشت

**Comment by farooqkz** [comment]
ولی به هر حال اگر خواستید اون ایده‌ای که دادم برای بچه دبستانی‌ها رو اجرا کنید یعنی
یک محیط تحت وب، بنده میتونم توی بک‌اند کمک کنم با پایتون و چری‌پای

البته قول نمیدم در این مورد

**Comment by Paptoos** [comment]
هر وقت بکندش آمده شد ، بگید توی ایشو #22 تا فرانتش رو هم آماده کنم

**Comment by farooqkz** [comment]
<div dir="rtl">

به لیست کار هام اینجا اضافه کردم:

https://notabug.org/farooqkz/todolist/issues

اما باید برام مشخص باشه از بک اند دقیقا چی میخواید؟
منظورم اینه که چه توابعی میخواید(توابع به صورت صفحه از طریق وب در دسترس هستند)

فنی تر بخوام بگم، اینه که پروتکل و طرز استفاده از API رو باید بهم بگید

**Comment by Paptoos** [comment]
یک تکست داده می شه ، تفسیرش می کنه ، و جواب رو بر می گردهنه ، توی صفحه وب یک تکست اریا داریم ، یک ترمینال برای جواب ، فقط نمی دونم ترمینال رو چجوری باید درست کرد ؟

**Comment by farooqkz** [comment]
در مورد سرور هم من یک عدد سرور رایگان لینوکسی می‌شناسم
که البته دسترسی اس‌اس‌اچ میده

فقط برای ثبت‌نامش باید یک معما باید حل بشه



> یک تکست داده می شه ، تفسیرش می کنه ، و جواب رو بر می گردهنه ، توی صفحه وب یک تکست اریا داریم ، یک ترمینال برای جواب ، فقط نمی دونم ترمینال رو چجوری باید درست کرد ؟

منظورت اینه که یک صفحه وب داشته باشیم با یک عدد تکست‌باکس و زمانی که کاربر دکمه اجرا رو فشار میده داخل یک عدد ترمینال نتیجه خروجی اجرا نمایش داده بشه همین درسته؟

**Comment by Paptoos** [comment]
بله

**Comment by Paptoos** [comment]
من هم می بینم می شه با پی اچ پی همچین چیزی نوشت یا نه
آخه من بکند ، پی اچ پی و یکم نود جی اس بلدم

**Comment by AshkanLaei** [comment]
دوستان اصلا نیازی به این کار ها نیست
همه چی سمت کلاینت انجام میشه

**Comment by Paptoos** [comment]
خب یعنی کمپایل شه ؟

**Comment by Paptoos** [comment]
به js?

**Comment by AshkanLaei** [comment]
آره همین کاری که با پایتون انجام میشه رو با جاوااسکریپت سمت کلاینت انجام میدیم

**Comment by Paptoos** [comment]
خیلی عالی ، بلاکی آماده شد آپلودش کن ، من هم ادیتور دسکتاپم به زودی آماده می شود

**Comment by Paptoos** [comment]
ایشو ها خیلی شلوغ شده ، درباره این هم صحبت کردیم ، پس می بندمش
