### ISSUE TITLE
استفاده از نیم‌فاصله برای جدا کردن کلمات از هم به‌جای خط زیر

### ISSUE THREAD

**Issue by farooqkz** [Ferdowsi-lang/Ferdowsi-Python-Interpreter#20]
<div dir="rtl">
با توجه به اینکه این یک زبان برنامه نویس فارسی هست من پیشنهاد میکنم استاندارد این باشه که
از نیم فاصله برای جدا کردن کلمات اسم یک متغیر استفاده بشه و نه خط زیر

خط زیر در انگلیسی استفاده میشه به خاطر اقتضای خط زبان اما ما که خطمون انگلیسی نیست
نیازی نداریم ازش استفاده کنیم و بنظرم نیم‌فاصله بهتره.

**Comment by Paptoos** [comment]
نوشتن نیم فاصله در ویندوز (ctrl + shift +2 ) خیلی سخت است و برنام نویسی به این زبان را سخت و آزاردهنده می کند

**Comment by farooqkz** [comment]
اوه ویندوزی ها رو کلا فراموش کرده بودم.
ولی به هر حال پیشنهاد میکنم حداقل از نیم‌فاصله در اسم متغیر‌ها بشه استفاده کرد

**Comment by AshkanLaei** [comment]
<div dir=rtl>آره منم همین ایده رو داشتم ولی به همون مشکل ویندوز برخوردم
یه کاری میشه کرد این که توی پروژه ادیتور یه میانبر جدید مثل shift+space در نظر بگیریم برای نیم‌فاصله
این طوری توی ادیتور راحته</div>

**Comment by parsampsh** [comment]
توی پی آر #54 این قابلیت اضافه شده

**Comment by Paptoos** [comment]
خیلی ممنون از @parsampsh
