### ISSUE TITLE
یک روش دیگه برای تعریف تابع

### ISSUE THREAD

**Issue by farooqkz** [Ferdowsi-lang/Ferdowsi-Python-Interpreter#23]
<div dir="rtl">

روش فعلی خوبه و معادل لامبدا در زبان های برنامه نویسی هست اما پیشنهاد میکنم روش زیر هم اضافه بشه

> شرح‌تابع سلام با‌ورودی نام‌کاربر
> چاپ «سلام، » + نام‌کاربر
> پایان‌شرح‌تابع

روی جزئیات میشه بحث کرد.
توجه کنید که **شرح‌تابع** و **با‌ورودی** و **پایان‌شرح‌تابع**  سه کلمه کلیدی برای تعریف تابع هستند و من فرض کردم که میشه از نیم‌فاصله مثل خط زیر در اسامی متغیر ها و کلمات کلیدی زبان استفاده کرد.

**Comment by Paptoos** [comment]
با آکولاد راحت تره
من هم همزمان همین رو نوشتم فقط با آکولاد
ورودی  های تابع خیلی سخته و فکر نکنم به این راحتی کار کنه

**Comment by farooqkz** [comment]
آخه آکولاد کاراکتر فارسی نیست فکر کنم

پرانتز چی؟

یا دندانه گزاری مثل پایتون که عادت های خوب رو هم توی یادگیرنده نهادینه کنه

**Comment by Paptoos** [comment]
پرانتز بیشتر برای ورودی

**Comment by Paptoos** [comment]
خیلی رو فارسی بودن کارکتر کار کنیم ، کار رو سخت می کنیم

**Comment by Paptoos** [comment]
تابع_بساز تست شروع
چاپ کن سلام
پایان
مثل EOF
که توی دستور cat لینوکس

**Comment by farooqkz** [comment]
پس پیشنهاد میکنم صدا زدن و دادن ورودی به تابع هم با پرانتز باشه
مثلا چاپ() بجای چاپ را اجرا کن

بعدش به جای پایان بنویسیم پایان‌تابع راحت تر نیست؟

**Comment by Paptoos** [comment]
چرا ولی سعی کنیم یک کلمه ای باشه
