### ISSUE TITLE
ارور ، فوری

### ISSUE THREAD

**Issue by amirghazi87** [Ferdowsi-lang/Ferdowsi-Python-Interpreter#33]
WARNING: 5 shift/reduce conflicts
در اجرای برنامه همچین وارنینگی می گیریم و این اصلا دست نیست
نتوستم دیباگ کنم و بفهمم مشکل از کجای برنامه است

**Comment by Paptoos** [comment]
بعد از کلی دیباگ فهمیدم مشکل از اینجاست :
	@_('PRINT expr')
	def expr(self, p):
		return ('print', p.expr)
ولی نمی دونم چطور درستش کنم ؟

**Comment by Paptoos** [comment]
اگر دقیق تر بگم مشکل از این کلمه است :
expr
خب معنی آل می ده ولی خطا چرا

**Comment by Paptoos** [comment]
اصلا کسی تا حالا پرینت رو تست کرده بود ؟ کار نمی کنه 🤣😐🤦‍♂️🤦‍♂️🤦‍♂️

**Comment by AshkanLaei** [comment]
<div dir=rtl>مشکل اینه که درباره تموم شدن دستور قسمت مشخصی وجود نداره
باید خط جدید رو ذخیره کنیم به عنوان END و بعدش آخر همه قائده های پارسر بنویسیم
هشدار برای اینه که نمیفهمه کجا دستور تموم شده و تو دستور بعدی هستیم</div>

**Comment by Paptoos** [comment]
فکر نکنم مشکل این باشه ، پس برای بقیه دستور ها چرا همچی مشکلی نداریم ؟

**Comment by Paptoos** [comment]
یک سوال : می توانم ایمیل شما را داشته باشم ؟
یک نکته هست که شاید خیلی کمک کنه

**Comment by Paptoos** [comment]
> 
> 
> یک سوال : می توانم ایمیل شما را داشته باشم ؟
> یک نکته هست که شاید خیلی کمک کنه

ایمیل من: amirghazi1387@gmail.com
