### ISSUE TITLE
دو مدل دستور چاپ؟!؟

### ISSUE THREAD

**Issue by mskf1383** [Ferdowsi-lang/Ferdowsi-Python-Interpreter#39]
<div dir="rtl">

چرا دو مدل دستور چاپ وجود داره؟
"سلام"
چاپ کن "سلام"
در ضمن دومی این ارور رو هم میده:
sly: Syntax error at line 1, token=NAME
</div>

**Comment by Paptoos** [comment]
مدل چاپ_کن درست تر است چون ممکن است استرینگ هر جای برنامه به برنامه داده شود 
فعلا چاپ کن مشکل دارد و در حال رفع باگ هستم

**Comment by farooqkz** [comment]
<div dir="rtl">

بله با پاپتوس موافقم و دومی بهتره.
مگر اینکه مثل لیسپ بخواید مدل REPL برید که احتمالا کار زبان‌ساز رو بسیار ساده‌تر میکنه.
