### ISSUE TITLE
فریمورک css فردوسی

### ISSUE THREAD

**Issue by Paptoos** [Ferdowsi-lang/Ferdowsi-Python-Interpreter#42]
خب داشتم یک فریمورک سی اس اس توسعه می دادم (سعی کردم خیلی کامل باشه) هنوز تکمیل نشده ، ولی گفتم می تونه فریمورک سی اس اس فردوسی باشه (:

**Comment by Paptoos** [comment]
البته هیچ ربطی به فارسی بودن نداره !

**Comment by AshkanLaei** [comment]
خب به نظرم بهتره یکم بیشتر توضیح بدی! چه شکلیه؟ یه عکس هم ازش بفرستی خوبه

**Comment by Paptoos** [comment]
چشم ، فعلا 2600 خطش رو نوشتم ، فایلش ر اینجا می فرستم ، اگر خوب بود توی این ارگانیزیشنی که توی گیت هاب ساختید ادم کنید

**Comment by Paptoos** [comment]
اینجا نمی شه آپلود کرد ، تی مگا آپلود می کنم ، لینک می فرستم

**Comment by Paptoos** [comment]
فایل css:
https://mega.nz/file/480GXJZS#x47-DfBjjy2-VuU3mVUoEvHl73TIsCx6G8SdUXxQaVE
فایل js :
https://mega.nz/file/oklkFBYQ#_Sg4poMhZcz9nnCadRd8cb9SriaG_4Oy78zebD0kQEk
به jquery هم نیاز داره

**Comment by Paptoos** [comment]
برای تست ، یک دکمه ایجاد کنید و کلاس های زیر را بهش بدهید:
btn , btn-allc , btn-circle
تستش کنید

**Comment by Paptoos** [comment]
دیشب بالاخره تونستنم یک سیستم گرید ساده با جاوااسکریپت بنویسم
فایل جدید js :
https://mega.nz/file/d49VnaJL#9f4TQYSGNgXLGW4Wv4pevtgjh6AkrSzcJSXhcSCFtIc

**Comment by Paptoos** [comment]
نحوه استفاده سیستم گرید:
col-1 to col-10
col-1-sm to col-10-sm
اس ام ها فقط در موبایل و تبلت های کوچک نشان داده می شوند
col-1-md to col-10-md
ام دی ها فقط در  تبلت و لپتاپ های کوچک نشان داده می شوند
col-1-sm to col-10-sm
ال جی ها فقط در لپتاپ و کامپیوتر ها  نشان داده می شوند
row رو هم که همه می شناسید

**Comment by Paptoos** [comment]
یک نکته رو خواستم اضافه کنم :
اینکه درسته من نمی تونم رقیب بوت استرپی باشم که توییتر پشتشه ولی هدف من با هدف بوت استرپ فرق داره
بوت استرپ کم کم داره از نیاز های اولیه یک برنامه نویس وب جدا می شه و داره نیاز های افراد خاص رو برطرف می کنه
به عنوان مثال هرکی توی سایتش یک لینکی به یکی از شبکه های اجتمعاعی یا حتی گیت هاب یا یوتوب داده ، ولی بوت استرپ اصلا برنامه برای اینکار نداره و برای این کار یک فایل سی اس اس بزرگ دیگه باید روی بار سایتتون بگذارید ، 
من این تو سعی کردم حداقل نیاز کاربر رو تامین کنم و اگر کاربر کار خاصی داره انجام می ده می تونه خودش سی اس اس بنویسه

**Comment by farooqkz** [comment]
<div dir="rtl">

> خب داشتم یک فریمورک سی اس اس توسعه می دادم (سعی کردم خیلی کامل باشه) هنوز تکمیل نشده ، ولی گفتم می تونه فریمورک سی اس اس فردوسی باشه (:

چرا باید فریم‌ورک سی‌اس‌اس خودتون رو توسعه بدید؟
مگر فریم‌ورک هایی که الآن وجود دارند چشون هست؟
علاوه بر اون اگر برای یک سایت ساده میخواید(همین مفسر و ترمینال خود فردوسی) شاید اصلا نیازی به فریم‌ورک هم نباشه و با خالص کار راه بیوفته.
مثلا ما برای پروژه سیب‌زمینی تخم مرغ چه برای جاوا اسکریپت و چه برای سی‌اس‌اس از فریم‌ورک استفاده نکردیم(دستکم فعلا) و از خالص استفاده کردیم.

**Comment by Paptoos** [comment]
فریمورک های حاضر دارند همینطور پیچیده تر می شن ، این فریمورک نمی خواهد نیاز های خاص کاربران خاص رو جواب بده قراره فریمروک برای برنامه نویسی های وبی که نیاز به یک چیز ساده و معقول دارند باشه

**Comment by farooqkz** [comment]
<div dir="rtl">

خود دانید اما میتونید از micro frameworks استفاده کنید.

**Comment by Paptoos** [comment]
این برای خود سایت استفاده نشده و کلا موضوعش جداستت

**Comment by Paptoos** [comment]
الان آماده است ، ریپوزیتوری اش رو هم توی حساب خودم ساختم  ،  اگر موفقید به فردوسی ترنسفرش کنم ؟

**Comment by AshkanLaei** [comment]
باشه

**Comment by Paptoos** [comment]
باشه ، الان می کنم
