### ISSUE TITLE
نام لاتین فردوسی Ferdowsi هست

### ISSUE THREAD

**Issue by farooqkz** [Ferdowsi-lang/Ferdowsi-Python-Interpreter#43]

**Comment by Paptoos** [comment]
نمی شه یقینا گفت چون پینگلیش نوع های نوشتن متوافتی داره
ولی باید ببینیم کدوم پر استفاده تر هست ؟

**Comment by farooqkz** [comment]
من دیدم ویکی‌پدیای انگلیسی از این استفاده کرده واسه همین گفتم.

**Comment by Paptoos** [comment]
حق با شماست من هم به همین نتیجه رسیدم 
باید شروع کنیم به تغییر دادن 😃

**Comment by Paptoos** [comment]
انجام شد
