### ISSUE TITLE
چند خطی

### ISSUE THREAD

**Issue by amirghazi87** [Ferdowsi-lang/Ferdowsi-Python-Interpreter#48]
من زیاد به sly مسلط نیستم
کسی می دونه چطوری می شه چند خطی توش کار کرد ؟
برای تابع ها شرط ها شمارنده ها و کامنت ها نیاز است

**Comment by parsampsh** [comment]
دو راه داریم:
راه اول اینه که در انتهای خط نقطه بزاریم(مثل سمی کالن) تا بتونیم چندخطی استفاده کنیم.
راه دوم اینه هرجا خواستیم بریم خط بعدی ی \ بزاریم.

یکی از اینا رو انتخاب کنید به من بگید تا پیادش کنم.

**Comment by AshkanLaei** [comment]
فردوسی الان غیرفعاله
دارم روش کار میکنم احتمالاً یکی دو هفته دیگه ریبوتش کنم
ولی برای اینکه بدونین میخوام چه شکلی باشه:
میخوام مثل بیسیک بسازمش
هم دستورات تک خطی داره هم چند خطی
برای چسبوندن دو خط از دونقطه و برای نصف کردن یه خط از زیرخط استفاده بشه
دقیقاً مثل ویژوال بیسیک

**Comment by amirghazi87** [comment]
به نظرم سینتکس خانواده سی می تونه بهتر باشه

**Comment by parsampsh** [comment]
> به نظرم سینتکس خانواده سی می تونه بهتر باشه

اخه فردوسی فارسیه و خیلی همخوانی پیدا نمیکنه با سینتکس سی.

**Comment by AshkanLaei** [comment]
> به نظرم سینتکس خانواده سی می تونه بهتر باشه

<p dir=rtl>اگه واقعاً نظرت اینه چند تا مثال بزن چون هرجور فکر میکنم جالب در نمیاد</p>

**Comment by seyedmm** [comment]
سینتکس پایتون چی؟ پایتون سینتکسش هم برای فارسی مناسب تره، هم ساده تره و اثر سادگی میشه کاربرای بیشتر

**Comment by amirghazi87** [comment]
به درد زبان فارسی نمی خوره

**Comment by AshkanLaei** [comment]
نیازی به بحث نیست من تصمیم گرفتم فردوسی رو تا جای ممکن به حرف زدن معمولی نزدیک بکنم. استفاده از دونقطه، سمی کالن و آکولاد با این مسئله مغایرت داره. اگه کسی حرفی نداره لطفاً این ایشو رو ببندین
