### ISSUE TITLE
چاپ شدن " ها همراه مقداری که چاپ میشه

### ISSUE THREAD

**Issue by parsampsh** [Ferdowsi-lang/Ferdowsi-Python-Interpreter#56]
در حال حاضر وقتی ی چیزی رو چاپ میکنیم:

```
"سلام دنیا"
```

خروجی اینه:

```
"سلام دنیا"
```

در حالی که انتظار میره اون
`"`
ها همراهش چاپ نشه.

**Comment by AshkanLaei** [comment]
توی پایتون هم همینطوریه وقتی یه مقدار برمیگرده به حالت برنامه نویسی نشون داده میشه. اگه از دستور چاپ استفاده بشه اونا نمیان.

**Comment by parsampsh** [comment]
اها. من حواسم به دستور چاپ نبود :)
ممنون
