### ISSUE TITLE
سوالاتی در باب زبان

### ISSUE THREAD

**Issue by EhsanAramide** [Ferdowsi-lang/Ferdowsi-Python-Interpreter#60]
سلام خسته نباشید
وقتی مستندات رو مطالعه کردم دو سوال برام پیش اومد خوشحال میشم اگر مقدور هست براتون پاسخی رو مطرح کنید

1. هدف از ساختن زبان فردوسی چیه و اصلا چرا ساخته شده؟
2. برنامه‌ی آینده‌ی شما برای توسعه‌ی این زبان چیه و به چه صورتی هست؟

خیلی لذت بردم از اینکه زبان فردوسی رو دیدم واقعا حالب بود برام مرسی بابت توسعه دادنش

**Comment by AshkanLaei** [comment]
سلام

خیلی ممنون

1. برای این ساختمش که هم خودم با ساز و کار زبان‌ها آشنا بشم و هم کسایی که تازه برنامه‌نویسی رو شروع کردن بتونن با زبان مادری خودشون برنامه بنویسن.
2. از همون اول قرار بود یه پروژهٔ ساده و غیرجدی باشه ولی احتمالش هست که چیزی مشابه این پروژه رو بعداً درست کنم.

ممنون، لطف دارین

**Comment by EhsanAramide** [comment]
ممنون از جوابت موفق باشی
امیدوارم بتونم در آینده همکاری‌هایی داشته باشیم
